[2024-04-08T01:13:06.286+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-01T17:41:34+00:00 [queued]>
[2024-04-08T01:13:06.295+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-01T17:41:34+00:00 [queued]>
[2024-04-08T01:13:06.296+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:13:06.313+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_archive> on 2024-04-01 17:41:34+00:00
[2024-04-08T01:13:06.318+0530] {standard_task_runner.py:60} INFO - Started process 49818 to run task
[2024-04-08T01:13:06.322+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'move_archive', 'manual__2024-04-01T17:41:34+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmpfnm25ux4']
[2024-04-08T01:13:06.324+0530] {standard_task_runner.py:88} INFO - Job 194: Subtask move_archive
[2024-04-08T01:13:06.372+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-01T17:41:34+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:13:06.438+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='move_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T17:41:34+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T17:41:34+00:00'
[2024-04-08T01:13:06.440+0530] {data_fetch_pipeline.py:121} ERROR - Error moving archive to //wsl.localhost/Ubuntu/home/lucky/Assign2: Destination directory does not exist.
[2024-04-08T01:13:06.440+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:13:06.446+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=move_archive, execution_date=20240401T174134, start_date=20240407T194306, end_date=20240407T194306
[2024-04-08T01:13:06.495+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:13:06.509+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
