[2024-03-09T04:32:04.234+0530] {processor.py:161} INFO - Started process (PID=2398) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:32:04.236+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:32:04.238+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:32:04.237+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:32:04.249+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:32:04.243+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:32:04.250+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:32:04.328+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.100 seconds
[2024-03-09T04:34:29.807+0530] {processor.py:161} INFO - Started process (PID=4465) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:34:29.810+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:34:29.812+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:34:29.811+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:34:29.819+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:34:29.816+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:34:29.821+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:34:29.872+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.073 seconds
[2024-03-09T04:35:29.676+0530] {processor.py:161} INFO - Started process (PID=5552) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:35:29.690+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:35:29.693+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:35:29.692+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:35:29.699+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:35:29.697+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:35:29.700+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:35:29.739+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.073 seconds
[2024-03-09T04:36:04.508+0530] {processor.py:161} INFO - Started process (PID=5953) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:04.511+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:36:04.513+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:36:04.512+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:04.519+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:36:04.517+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:36:04.520+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:04.601+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.107 seconds
[2024-03-09T04:36:41.933+0530] {processor.py:161} INFO - Started process (PID=6733) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:41.936+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:36:41.938+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:36:41.937+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:41.963+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:36:41.950+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:36:41.965+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:36:42.043+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.119 seconds
[2024-03-09T04:37:15.348+0530] {processor.py:161} INFO - Started process (PID=7194) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:15.362+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:37:15.366+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:37:15.365+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:15.376+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:37:15.372+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:37:15.378+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:15.439+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.100 seconds
[2024-03-09T04:37:47.831+0530] {processor.py:161} INFO - Started process (PID=7573) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:47.835+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:37:47.838+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:37:47.837+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:47.847+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:37:47.845+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:37:47.848+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:37:47.906+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.083 seconds
[2024-03-09T04:38:19.282+0530] {processor.py:161} INFO - Started process (PID=7965) to work on /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:38:19.286+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/data_fetch_pipeline.py.py for tasks to queue
[2024-03-09T04:38:19.290+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:38:19.288+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:38:19.300+0530] {logging_mixin.py:188} INFO - [2024-03-09T04:38:19.297+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/data_fetch_pipeline.py.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/data_fetch_pipeline.py.py", line 283, in <module>
    "execution_count": null,
NameError: name 'null' is not defined
[2024-03-09T04:38:19.302+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/data_fetch_pipeline.py.py
[2024-03-09T04:38:19.355+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/data_fetch_pipeline.py.py took 0.081 seconds
