[2024-03-10T22:14:03.863+0530] {processor.py:161} INFO - Started process (PID=22644) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T22:14:03.865+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T22:14:03.866+0530] {logging_mixin.py:188} INFO - [2024-03-10T22:14:03.865+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T22:14:03.892+0530] {logging_mixin.py:188} INFO - [2024-03-10T22:14:03.887+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T22:14:03.893+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T22:14:03.929+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.069 seconds
[2024-03-10T23:37:22.154+0530] {processor.py:161} INFO - Started process (PID=22983) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:37:22.157+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:37:22.160+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:37:22.159+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:37:22.174+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:37:22.171+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:37:22.176+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:37:22.259+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.112 seconds
[2024-03-10T23:38:32.691+0530] {processor.py:161} INFO - Started process (PID=24252) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:38:32.695+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:38:32.698+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:38:32.697+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:38:32.708+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:38:32.706+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:38:32.709+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:38:32.763+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.078 seconds
[2024-03-10T23:39:12.561+0530] {processor.py:161} INFO - Started process (PID=24768) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:12.574+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:39:12.576+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:39:12.575+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:12.582+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:39:12.580+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:39:12.583+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:12.625+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.069 seconds
[2024-03-10T23:39:51.717+0530] {processor.py:161} INFO - Started process (PID=25424) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:51.720+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:39:51.725+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:39:51.724+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:51.740+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:39:51.736+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:39:51.742+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:39:51.823+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.112 seconds
[2024-03-10T23:40:29.311+0530] {processor.py:161} INFO - Started process (PID=26129) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:40:29.325+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:40:29.329+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:40:29.327+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:40:29.340+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:40:29.338+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:40:29.342+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:40:29.430+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.125 seconds
[2024-03-10T23:41:05.759+0530] {processor.py:161} INFO - Started process (PID=26609) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:05.771+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:41:05.774+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:41:05.773+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:05.782+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:41:05.780+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:41:05.783+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:05.821+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.067 seconds
[2024-03-10T23:41:41.310+0530] {processor.py:161} INFO - Started process (PID=27064) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:41.324+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:41:41.326+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:41:41.325+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:41.333+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:41:41.331+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:41:41.334+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:41:41.369+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.064 seconds
[2024-03-10T23:42:20.477+0530] {processor.py:161} INFO - Started process (PID=27940) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:20.481+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:42:20.483+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:42:20.482+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:20.491+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:42:20.489+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:42:20.491+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:20.534+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.062 seconds
[2024-03-10T23:42:57.675+0530] {processor.py:161} INFO - Started process (PID=28428) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:57.689+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:42:57.691+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:42:57.690+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:57.700+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:42:57.697+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:42:57.702+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:42:57.760+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.092 seconds
[2024-03-10T23:43:33.302+0530] {processor.py:161} INFO - Started process (PID=28973) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:43:33.315+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:43:33.318+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:43:33.317+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:43:33.327+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:43:33.325+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:43:33.329+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:43:33.379+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.099 seconds
[2024-03-10T23:44:08.468+0530] {processor.py:161} INFO - Started process (PID=29717) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:08.481+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:44:08.483+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:44:08.483+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:08.489+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:44:08.488+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:44:08.490+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:08.522+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.059 seconds
[2024-03-10T23:44:43.128+0530] {processor.py:161} INFO - Started process (PID=30182) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:43.141+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:44:43.143+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:44:43.142+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:43.150+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:44:43.148+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:44:43.150+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:44:43.186+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.066 seconds
[2024-03-10T23:45:20.428+0530] {processor.py:161} INFO - Started process (PID=30675) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:20.431+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:45:20.433+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:45:20.432+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:20.443+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:45:20.440+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:45:20.444+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:20.509+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.087 seconds
[2024-03-10T23:45:56.939+0530] {processor.py:161} INFO - Started process (PID=31567) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:56.944+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:45:56.956+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:45:56.954+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:56.978+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:45:56.975+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:45:56.980+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:45:57.098+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.178 seconds
[2024-03-10T23:46:36.676+0530] {processor.py:161} INFO - Started process (PID=32041) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:46:36.681+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:46:36.685+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:46:36.683+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:46:36.694+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:46:36.691+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:46:36.697+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:46:36.741+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.071 seconds
[2024-03-10T23:47:16.088+0530] {processor.py:161} INFO - Started process (PID=32516) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:16.097+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:47:16.104+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:47:16.102+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:16.125+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:47:16.121+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:47:16.127+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:16.244+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.177 seconds
[2024-03-10T23:47:56.729+0530] {processor.py:161} INFO - Started process (PID=33413) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:56.731+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:47:56.732+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:47:56.732+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:56.735+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:47:56.735+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:47:56.736+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:47:56.756+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.030 seconds
[2024-03-10T23:48:30.747+0530] {processor.py:161} INFO - Started process (PID=33876) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:48:30.749+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:48:30.751+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:48:30.750+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:48:30.757+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:48:30.755+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:48:30.757+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:48:30.783+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.040 seconds
[2024-03-10T23:49:23.394+0530] {processor.py:161} INFO - Started process (PID=34923) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:49:23.405+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:49:23.406+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:49:23.406+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:49:23.411+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:49:23.410+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:49:23.411+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:49:23.432+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.041 seconds
[2024-03-10T23:50:17.838+0530] {processor.py:161} INFO - Started process (PID=35636) to work on /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:50:17.850+0530] {processor.py:830} INFO - Processing file /home/lucky/airflow/dags/analytics.py for tasks to queue
[2024-03-10T23:50:17.851+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:50:17.850+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:50:17.856+0530] {logging_mixin.py:188} INFO - [2024-03-10T23:50:17.854+0530] {dagbag.py:348} ERROR - Failed to import: /home/lucky/airflow/dags/analytics.py
Traceback (most recent call last):
  File "/home/lucky/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lucky/airflow/dags/analytics.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-03-10T23:50:17.856+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/lucky/airflow/dags/analytics.py
[2024-03-10T23:50:17.883+0530] {processor.py:183} INFO - Processing /home/lucky/airflow/dags/analytics.py took 0.048 seconds
