[2024-04-08T01:44:45.723+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:13:45+00:00 [queued]>
[2024-04-08T01:44:45.732+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:13:45+00:00 [queued]>
[2024-04-08T01:44:45.732+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:44:45.748+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_archive> on 2024-04-07 20:13:45+00:00
[2024-04-08T01:44:45.754+0530] {standard_task_runner.py:60} INFO - Started process 78566 to run task
[2024-04-08T01:44:45.757+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'move_archive', 'manual__2024-04-07T20:13:45+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmpwhbo7r15']
[2024-04-08T01:44:45.759+0530] {standard_task_runner.py:88} INFO - Job 280: Subtask move_archive
[2024-04-08T01:44:45.789+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:13:45+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:44:45.844+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='move_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T20:13:45+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T20:13:45+00:00'
[2024-04-08T01:44:45.846+0530] {data_fetch_pipeline.py:121} ERROR - Error moving archive to //wsl.localhost/Ubuntu/home/lucky/Assign2: Destination directory does not exist.
[2024-04-08T01:44:45.846+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:44:45.850+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=move_archive, execution_date=20240407T201345, start_date=20240407T201445, end_date=20240407T201445
[2024-04-08T01:44:45.890+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:44:45.903+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
