[2024-04-08T01:13:27.971+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T19:19:23+00:00 [queued]>
[2024-04-08T01:13:27.993+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T19:19:23+00:00 [queued]>
[2024-04-08T01:13:27.994+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:13:28.137+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_archive> on 2024-04-07 19:19:23+00:00
[2024-04-08T01:13:28.347+0530] {standard_task_runner.py:60} INFO - Started process 50100 to run task
[2024-04-08T01:13:28.426+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'move_archive', 'manual__2024-04-07T19:19:23+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmp0txidfxh']
[2024-04-08T01:13:28.451+0530] {standard_task_runner.py:88} INFO - Job 197: Subtask move_archive
[2024-04-08T01:13:29.758+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T19:19:23+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:13:30.461+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='move_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T19:19:23+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T19:19:23+00:00'
[2024-04-08T01:13:30.465+0530] {data_fetch_pipeline.py:121} ERROR - Error moving archive to //wsl.localhost/Ubuntu/home/lucky/Assign2: Destination directory does not exist.
[2024-04-08T01:13:30.465+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:13:30.481+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=move_archive, execution_date=20240407T191923, start_date=20240407T194327, end_date=20240407T194330
[2024-04-08T01:13:30.569+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:13:30.597+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
